name: course_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^3.0.8
  flutter_swiper: ^1.1.4 #轮播插件
  flutter_screenutil: ^0.5.1 #屏幕插件
  url_launcher: ^5.0.1   #拨打电话
  flutter_easyrefresh: ^2.0.4 #上拉刷新
  provide: ^1.0.2     #状态管理
  fluttertoast: #^3.0.1
  fluro: ^1.5.1 #路由
  cached_network_image: ^2.0.0   #图片缓存
  common_utils: ^1.1.3
  shared_preferences: ^0.5.1
  flutter_spinkit: ^4.1.1
  flutter_datetime_picker: ^1.3.1  #日期时间
  image_pickers:   ^1.0.7+1        #选择图片
  liquid_progress_indicator: ^0.3.2 #进度条
  progress_dialog: ^1.2.0
  sqflite: ^1.2.0
  path_provider: ^1.5.1
  connectivity: ^0.4.6+2  #网络状态
#  image_picker: ^0.6.3
  direct_select: ^1.0.0
#  flutter_jpush: ^0.0.4 #极光推送
  flutter_local_notifications: ^1.1.5+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  #我添加的json_serializable依赖
  build_runner: ^1.0.0
  json_serializable: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bg_swiper.png
    - assets/img/appIcon.png
    - assets/bgk/bgk0.jpg
    - assets/bgk/bgk1.jpg
    - assets/bgk/backgroud.jpg
    - assets/img/加载失败.png
    - assets/img/pic_error.png
    - assets/img/网络失败.png
    - assets/img/netpic_error.png
    - assets/img/dpic.png
    - assets/img/user.png
    - assets/img/sex0.png
    - assets/img/sex1.png
    - assets/img/性别v.png
    - assets/img/性别男.png
    - assets/img/add.png
    - assets/img/添加相片.png
    - assets/img/公告-暂无内容.png
    - assets/img/暂无公告.png
    - assets/img/暂无公告icon.png
    - assets/img/zanwugg@2x.png
    - assets/img/nodata1.png
    - assets/img/nodata2.png
    - assets/img/nodata3.png
    - assets/img/nodata4.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: appIconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: appIconFont2
      fonts:
        - asset: assets/fonts2/iconfont.ttf